# Use an official Python runtime as a parent image
FROM python:3.9

# Adding backend directory to make absolute filepaths consistent across services
WORKDIR /backend

# Install Python dependencies
COPY requirements.txt /backend
RUN pip3 install --upgrade pip -r requirements.txt

# Add the rest of the code
COPY . /backend

# Make port 5000 available for the app
EXPOSE 5000